"""empty message

Revision ID: 3020953f47c6
Revises: 
Create Date: 2020-03-12 23:48:27.999109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3020953f47c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oldmaninfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('medical_history', sa.String(length=30), nullable=True),
    sa.Column('allergy', sa.String(length=30), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('drugs', sa.String(length=30), nullable=True),
    sa.Column('treatment', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qrcode',
    sa.Column('qr_code_id', sa.String(length=50), nullable=False),
    sa.Column('old_man_info', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['old_man_info'], ['oldmaninfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qr_code_id')
    )
    op.create_table('phonenumber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('q_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['q_id'], ['qrcode.qr_code_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumber')
    op.drop_table('qrcode')
    op.drop_table('oldmaninfo')
    # ### end Alembic commands ###
